#!/bin/sh

echo "\033[44;37;1mCleaning libOpenCOR...\033[0m"

appDir=$(cd $(dirname $0); pwd)

for i in _skbuild build src/bindings/python/libopencor.egg-info; do
    rm -fr $appDir/$i
done

echo "\033[42;37;1mAll done!\033[0m"
