#!/bin/sh

if [ "$1" = "all" ]; then
    echo "\033[44;37;1mCleaning all of libOpenCOR...\033[0m"
else
    echo "\033[44;37;1mCleaning libOpenCOR...\033[0m"
fi

appDir=$(cd $(dirname $0); pwd)/..

find $appDir -type f -name .DS_Store -exec rm -f {} \; 2> /dev/null
find $appDir -type d \( -name .pytest_cache -o -name __pycache__ -o -name _skbuild -o -name build \) -exec rm -fr {} \; 2> /dev/null

if [ "$1" = "all" ]; then
    rm -fr $appDir/prebuilt/* > /dev/null 2>&1
fi

echo "\033[42;37;1mAll done!\033[0m"
